#!/bin/bash
# kuidas ta isegi presidentiks meile sattus??
aasta=2016
president="Kersti Kaljulaid"
lause_keskosa=". aastal valiti Eesti presidentiks "
lause="$aasta$lause_keskosa $president"

echo $lause
